import os
import pygame

# 플레이어 시야 스케일 (1.0 = 기본 시야)
PLAYER_VIEW_SCALE = 0.9

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# 배경 크기
BG_WIDTH = int(1600 * PLAYER_VIEW_SCALE)
BG_HEIGHT = int(1200 * PLAYER_VIEW_SCALE)

# 경로
BASE_DIR = os.path.dirname(__file__)
ASSET_DIR = os.path.join(BASE_DIR, "Asset")

# 속도
NORMAL_MAX_SPEED = 6
SPRINT_MAX_SPEED = 9

# 사운드 설정
WALK_VOLUME = 0.5
GUN1_VOLUME = 1.0
GUN2_VOLUME = 1.0
GUN3_VOLUME = 1.0

# Gun1, Gun2, Gun3 설정
GUN1_FIRE_DELAY = 400
GUN2_FIRE_DELAY = 150
GUN3_FIRE_DELAY = 700

GUN1_RECOIL = 7
GUN2_RECOIL = 8
GUN3_RECOIL = 10

GUN1_SPEED_PENALTY = 0.05
GUN2_SPEED_PENALTY = 0.10
GUN3_SPEED_PENALTY = 0.10

# 무기별 탄퍼짐 (도 단위)
GUN1_SPREAD_ANGLE = 10
GUN2_SPREAD_ANGLE = 20
GUN3_SPREAD_ANGLE = 35
GUN3_NUM_BULLETS = 15

GUN1_DISTANCE_FROM_CENTER = PLAYER_VIEW_SCALE * 45
GUN2_DISTANCE_FROM_CENTER = PLAYER_VIEW_SCALE * 50
GUN3_DISTANCE_FROM_CENTER = PLAYER_VIEW_SCALE * 35

# Gun1, Gun2, Gun3 zoom level 초기값
GUN1_ZOOM_LEVEL = -1.0
GUN2_ZOOM_LEVEL = -300.0
GUN3_ZOOM_LEVEL = -7.0

# Gun1 zoom limits
GUN1_MIN_ZOOM = -5.0
GUN1_MAX_ZOOM = -0.001

# Gun2 zoom limits
GUN2_MIN_ZOOM = -500.0
GUN2_MAX_ZOOM = -250.0

# Gun3 zoom limits
GUN3_MIN_ZOOM = -20.0
GUN3_MAX_ZOOM = -4.0

# 무기별 zoom 비율 (10%로 설정)
GUN1_ZOOM_RATIO = 0.10
GUN2_ZOOM_RATIO = 0.10
GUN3_ZOOM_RATIO = 0.10

# 폰트
pygame.font.init()
DEBUG_FONT = pygame.font.SysFont('malgungothic', 24)

# OBJ 경로
OBJ_PATHS = {
    1: os.path.join(ASSET_DIR, "3DObject", "Gun13DObject.obj"),
    2: os.path.join(ASSET_DIR, "3DObject", "Gun23DObject.obj"),
    3: os.path.join(ASSET_DIR, "3DObject", "Gun33DObject.obj"),
}